//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncios
    {
        public int IdAnuncio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public float Horas { get; set; }
        public int Usuario1 { get; set; }
        public Nullable<int> Usuario2 { get; set; }
        public int Estado { get; set; }
    
        public virtual cState cState { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
