//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oSesion
    {
        public int IdSesion { get; set; }
        public int Valor { get; set; }
    }
}
