//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6_P3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class p6dbEntities : DbContext
    {
        public p6dbEntities()
            : base("name=p6dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anuncios> Anuncios { get; set; }
        public virtual DbSet<cState> cState { get; set; }
        public virtual DbSet<oSesion> oSesion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
